language: crystal
env:
  global:
  - GH_REF: github.com/icyleaf/wasp
  - secure: R82uqr7beYlWx6R6/If9GMWL+0BnQZEuON6Y7S1JzX23+kqG56AayZvjfiJEOCFyQdg7P6iJDud6KTbFos3NMj6lEuX3uHOqaJVMtBFX6g/fEuhXwap9eUHUu9Dum2uh62uSVAbP9wsJ8AwDLrTCuIdt+FJUCjB2SMxQZTj6kEjoYHxai4JtW6O2rX2QIPkPiBWzbviNpkushJ9/GFZuTc+W/zGvK7wOan7lVXX9xkGVxTzXJjGPS8Pl8i9vIjlL6WWsVRsv9F4M8bR5ByJaV6vWCvJXgBJabLSJDMKMuBny54hQ0O5vsbaLJPKj94pu2VQ6KAOR1XDbmI0PqbniwgPj1B/H89Z1c6PoLiXugcPIC6C46ggbgnN6bYyAX3CsTYxzrObnwT59umOzbhm5qgbwzmbjpG8OAuDiP5Ic3SbW09Jc/Ad5iClJI+suOWcfXplKojlwCqG46cB8DA+w16x5gQzgYNc/nJ7wLm5FPtPDHZqj/c0WBD83A+bCwKB8fDpvswusCg7qOIPMffXIT0PYX/1yeFiVCAS1jXBg+st/CvXVWMBufWSsc4X7ufnpB8/77GWQjPu/IwYeX9sgrFYHqFAKmNkZbFXc2XsYJe9NAOaMKdhA7VjkT5IOgUvJJmSkIyZDUyAHmoJgHojbVcaJjFiKX+6Wl3zNBXpVEm0=
script:
- crystal build --release src/wasp.cr -o wasp
after_script:
- COMMIT_HASH=$(git rev-parse --short HEAD)
- ./wasp build --source docs
- cd docs/public
- git config --global user.name "icyleaf"
- git config --global user.email "icyleaf.cn@gmail.com"
- git init
- git remote add origin "https://${GH_TOKEN}@${GH_REF}.git"
- git fetch origin
- git reset origin/gh-pages
- git add .
- git commit --allow-empty -m "Updating documents from master#${COMMIT_HASH}"
- git push origin HEAD:gh-pages