version: 2
jobs:
  build:
    docker:
      - image: crystallang/crystal
    environment:
      DOCS_PATH: "docs"
      GIT_USER: "icyleaf"
      GIT_EMAIL: "icyleaf.cn@gmail.com"
      GIT_REPO: "git@github.com:icyleaf/wasp.git"
    branches:
      ignore:
        - gh-pages
    working_directory: ~/wasp
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: crystal deps
      - run:
          name: "Spec"
          command: crystal spec
      - run:
          name: "Build wasp"
          command: crystal build --release -o wasp src/wasp.cr
      - run:
          name: "Generate static site"
          command: ./wasp build --source $DOCS_PATH --verbose
      - deploy:
          name: "Upload to gh-page"
          command: |
            git config --global user.name "$GIT_USER"
            git config --global user.email "$GIT_EMAIL"
            cd "${DOCS_PATH}/public"
            git init
            git remote add origin $GIT_REPO
            git fetch origin
            git reset origin/gh-pages
            git add -A .
            git commit --allow-empty -m "Updating documents from master#${COMMIT_HASH}"
            git push origin HEAD:gh-pages