title: "Hello Wasp"
subtitle: "A Static Site Generator"
description: "Wasp is a Static Site Generator writes in Crystal."
timezone: "Asia/Shanghai"

base_url: "http://icyleaf.github.io/wasp"
# base_url: "/"
# theme: "nest"

permalink: ":year/:month/:title/"
per_page: 10
