title: "Hello Wasp"
subtitle: "A Static Site Generator"
description: "Wasp is a Static Site Generator written in Crystal."
timezone: "Asia/Shanghai"

base_url: "https://icyleaf.github.io/wasp/"
# theme: "nest"

permalink: ":section/:title/"
ugly_url: false
per_page: 10
